version: '2'
# define all services
services:
  # our service is called laravel ;-)
  appi:
    # we want to use the image which is build from our Dockerfile
    #build: .
    image: appi
    # volumes, let's see if I can point it to local
    volumes:
      - /app:/var/www/html/
    # apache is running on port 80 but we want to expose this to port 4000 on our local machine
    ports:
      - "4000:80"
    # we depending on the mysql backend
    depends_on:
      - appidb
  appidb:
    # we use the mysql base image, version 5.6.36
    image: mysql:5.6.36
    # we mount a datavolume to make sure we don't loose data
    volumes:
      - db_data:/var/lib/mysql
    # setting some envvars to create the DB
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=appi
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
volumes:
  db_data:

